FROM ubuntu
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/embed/apache-tomcat-9.0.73-embed.tar.gz /tmp
ADD apache-tomcat-9.0.73-embed.tar.gz /tmp/

# RUN apt-get update && \
#    apt-get install -y unzip \
#    unzip /tmp/apache-tomcat-9.0.73.zip -d /tmp/apache_server